routes/admin.php
<?php


Route::get('home', 'HomeController@index')->name('home.index');


Route::resource('estados', 'EstadoController'); //admin.estados.index


Route::resource('areas', 'AreaController');


Route::resource('tipos_tramite', 'TipoTramiteController');

Route::resource('tramites', 'TramiteController');

Route::resource('cargos', 'CargoController');

routes/web.php
<?php

Route::group(['middleware' => 'guest'], function () {
    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');

// Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
});

Route::group(['middleware' => 'auth'], function () {

    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['middleware' => 'admin'], function () {
        // Registration Routes...
        Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'Auth\RegisterController@register');

        // Users Routes...
        Route::get('/users/index', 'UserController@index')->name('admin.users.index');
        Route::get('/user/destroy/{id}', 'UserController@destroy');

    });
});

//Route::get('/nuevoUsuario', 'UserController@index');

//Route::post('/store', 'UserController@store');

app/Estado.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Estado extends Model
{
    use SoftDeletes;

    protected $table = 'estados';

    protected $fillable = ['estado'];

    protected $dates = ['deleted_at'];
}

app/Http/Controllers/Admin/EstadoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Estado;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class EstadoController extends Controller
{

    public function index()
    {
        $estados = Estado::orderBy('estado')->paginate(5);

        return view('admin.estados.index', compact('estados'));
    }

    public function create()
    {
        return view('admin.estados.create');
    }

    public function store(Request $request)
    {
        Estado::create([
            'estado' => $request->input('estado'),
        ]);

        return redirect(route('admin.estados.index'))->with('success', 'Estado Creado correctamente');
    }

    public function show($id)
    {
        $estado = Estado::where('id', $id)->first();

        return view('admin.estados.delete', compact('estado'));
    }

    public function edit($id)
    {
        $estado = Estado::where('id', $id)->first();

        return view('admin.estados.edit', compact('estado'));
    }


    public function update(Request $request, $id)
    {
        Estado::where('id', $id)->update([
            'estado' => $request->input('estado')
        ]);

        return redirect(route('admin.estados.index'))->with('success', 'Estado actualizado correctamente');
    }

    public function destroy($id)
    {
        Estado::where('id', $id)->delete();

        return redirect(route('admin.estados.index'))->with('success', 'Estado eliminado correctamente');
    }
}

resources/views/admin/estados/create.blade.php
@extends('layouts.admin')

@section('title')

    Nueva Estado

@endsection

@section('content')


    <div class="card card-info">

        <!-- form start -->
        <form method="POST" action="{{route('admin.estados.store')}}" class="form-horizontal">
            @csrf

            <div class="card-body">
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Estado</label>

                    <div class="col-sm-12">
                        <input type="text" class="form-control" name="estado" value="{{old('estado')}}" placeholder="-" autofocus required autocomplete="off">
                    </div>
                </div>
               
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <input type="submit" class="btn btn-info float-right"  value="Crear"/>
                <a href="{{route('admin.estados.index')}}" class="btn btn-default">Cancel</a>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>

@endsection

resources/views/admin/estados/delete.blade.php
@extends('layouts.admin')

@section('title')

    Eliminar Estado


@endsection

@section('content')


    <div class="card card-info">

        <div class="card-body">

            <!-- form start -->
            <form method="POST" action="{{route('admin.estados.destroy', $estado->id)}}" class="form-horizontal">
                @csrf
                @method('delete')

                <div class="alert alert-danger text-center" style="overflow: hidden;">

                    ¿ Eliminar el estado <strong>{{$estado->estado}}</strong>?

                </div>

                <a href="{{route('admin.estados.index')}}" class="btn btn-default float-left">Cancel</a>

                <input type="submit" class="btn btn-danger float-right" value="Eliminar"/>

                <!-- /.card-footer -->
            </form>

        </div>
    </div>

@endsection

resources/views/admin/estados/edit.blade.php
@extends('layouts.admin')

@section('title')

    Editar Estado


@endsection

@section('content')


    <div class="card card-info">

        <!-- form start -->
        <form method="POST" action="{{route('admin.estados.update', $estado->id)}}" class="form-horizontal">
            @csrf
            @method('patch')

            <div class="card-body">
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Estado</label>

                    <div class="col-sm-12">
                        <input type="text" class="form-control" name="estado" value="{{ $estado->estado }}" placeholder="..." autofocus required autocomplete="off">
                    </div>
                </div>
               

            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <input type="submit" class="btn btn-warning float-right"  value="Editar"/>
                <a href="{{route('admin.estados.index')}}" class="btn btn-default">Cancel</a>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>


@endsection

resources/views/admin/estados/index.blade.php
@extends('layouts.admin')

@section('title')

    Estados

    <a href="{{route('admin.estados.create')}}" class="btn btn-info btn-sm">
        <i class="fa fa-plus" aria-hidden="true"></i>
    </a>

@endsection

@section('content')



    <div class="card">

        @if(session()->has('success'))
            <div class="alert alert-success">
                {{session()->get('success')}}
            </div>
        @endif

        <div class="card-body">
            <table class="table-bordered table">
                <thead>
                <tr>
                    <td class="text-center">Estado</td>
                    <td class="text-center">Acciones</td>
                </tr>
                </thead>
                <tbody>
                @foreach($estados as $e)
                    <tr class="text-center">
                        <th>
                            {{$e->estado}}
                        </th>

                        <th>
                            <div class="btn-group">
                                <i class="fa fa-list" aria-hidden="true" data-toggle="dropdown"
                                   aria-expanded="false" style="cursor: pointer; color: #1d68a7">
                                </i>

                                <div class="dropdown-menu" role="menu" x-placement="bottom-start"
                                     style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(67px, 38px, 0px);">
                                    <a class="dropdown-item" href="{{route('admin.estados.edit', $e->id)}}">
                                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        Editar
                                    </a>
                                    <a class="dropdown-item" href="{{route('admin.estados.show', $e->id)}}">
                                        <i class="fa fa-trash" aria-hidden="true"></i>
                                        Eliminar
                                    </a>
                                </div>
                            </div>
                        </th>
                    </tr>
                @endforeach

                </tbody>
            </table>
            {{ $estados->links() }}
        </div>

    </div>


@endsection