routes/admin.php
<?php


Route::get('home', 'HomeController@index')->name('home.index');


Route::resource('estados', 'EstadoController'); //admin.estados.index


Route::resource('areas', 'AreaController');


Route::resource('tipos_tramite', 'TipoTramiteController');

Route::resource('tramites', 'TramiteController');

Route::resource('cargos', 'CargoController');

routes/web.php
<?php

Route::group(['middleware' => 'guest'], function () {
    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');

// Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
});

Route::group(['middleware' => 'auth'], function () {

    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['middleware' => 'admin'], function () {
        // Registration Routes...
        Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'Auth\RegisterController@register');

        // Users Routes...
        Route::get('/users/index', 'UserController@index')->name('admin.users.index');
        Route::get('/user/destroy/{id}', 'UserController@destroy');

    });
});

//Route::get('/nuevoUsuario', 'UserController@index');

//Route::post('/store', 'UserController@store');

resources/views/admin/tipos_tramite/create.blade.php
@extends('layouts.admin')
@section('title')

    Nuevo Tipo de Trámite

@endsection

@section('content')


    <div class="card card-info">

        <!-- form start -->
        <form method="POST" action="{{route('admin.tipos_tramite.store')}}" class="form-horizontal">
            @csrf

            <div class="card-body">
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Tipo de Trámite</label>

                    <div class="col-sm-12">
                        <input type="text" class="form-control" name="tipo_tramite" value="{{old('tipo')}}" placeholder="-" autofocus required autocomplete="off">
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <input type="submit" class="btn btn-info float-right"  value="Crear"/>
                <a href="{{route('admin.tipos_tramite.index')}}" class="btn btn-default">Cancel</a>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>

@endsection

resources/views/admin/tipos_tramite/delete.blade.php
@extends('layouts.admin')

@section('title')

    Eliminar Tipo de Trámite


@endsection

@section('content')


    <div class="card card-info">

        <div class="card-body">

            <!-- form start -->
            <form method="POST" action="{{route('admin.tipos_tramite.destroy', $tipo_tramite->id)}}" class="form-horizontal">
                @csrf
                @method('delete')

                <div class="alert alert-danger text-center" style="overflow: hidden;">

                    ¿ Eliminar el tipo de tramite <strong>{{$tipo_tramite->tipo_tramite}}</strong>?

                </div>

                <a href="{{route('admin.tipos_tramite.index')}}" class="btn btn-default float-left">Cancel</a>

                <input type="submit" class="btn btn-danger float-right" value="Eliminar"/>

                <!-- /.card-footer -->
            </form>

        </div>
    </div>

@endsection

resources/views/admin/tipos_tramite/edit.blade.php
@extends('layouts.admin')

@section('title')

    Editar Tipo de Trámite


@endsection

@section('content')


    <div class="card card-info">

        <!-- form start -->
        <form method="POST" action="{{route('admin.tipos_tramite.update', $tipo_tramite->id)}}" class="form-horizontal">
            @csrf
            @method('patch')

            <div class="card-body">
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Tipo de Trámite</label>

                    <div class="col-sm-12">
                        <input type="text" class="form-control" name="tipo_tramite" value="{{ $tipo_tramite->tipo_tramite }}" autofocus required autocomplete="off">
                    </div>
                </div>
               

            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <input type="submit" class="btn btn-warning float-right"  value="Editar"/>
                <a href="{{route('admin.tipos_tramite.index')}}" class="btn btn-default">Cancel</a>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>


@endsection

resources/views/admin/tipos_tramite/index.blade.php
@extends('layouts.admin')

@section('title')

    Tipos de Trámite

    <a href="{{route('admin.tipos_tramite.create')}}" class="btn btn-info btn-sm">
        <i class="fa fa-plus" aria-hidden="true"></i>
    </a>

@endsection

@section('content')


    <div class="card">

        <div class="card-body">
            <table class="table-bordered table">
                <thead>
                <tr>
                    <td class="text-center">Tipo de Trámite</td>
                    <td class="text-center">Acciones</td>
                </tr>
                </thead>
                <tbody>
                @foreach($tipos_tramite as $t)
                    <tr class="text-center">
                        <th>
                            {{$t->tipo_tramite}}
                        </th>
                       
                        <th>
                            <div class="btn-group">
                                <i class="fa fa-list" aria-hidden="true" data-toggle="dropdown"
                                   aria-expanded="false" style="cursor: pointer; color: #1d68a7">
                                </i>

                                <div class="dropdown-menu" role="menu" x-placement="bottom-start"
                                     style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(67px, 38px, 0px);">
                                    <a class="dropdown-item" href="{{route('admin.tipos_tramite.edit', $t->id)}}">
                                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        Editar
                                    </a>
                                    <a class="dropdown-item" href="{{route('admin.tipos_tramite.show', $t->id)}}">
                                        <i class="fa fa-trash" aria-hidden="true"></i>
                                        Eliminar
                                    </a>
                                </div>
                            </div>
                        </th>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>

    </div>


@endsection