routes/admin.php
<?php


Route::get('home', 'HomeController@index')->name('home.index');


Route::resource('estados', 'EstadoController'); //admin.estados.index


Route::resource('areas', 'AreaController');


Route::resource('tipos_tramite', 'TipoTramiteController');

Route::resource('tramites', 'TramiteController');

Route::resource('cargos', 'CargoController');

routes/web.php
<?php

Route::group(['middleware' => 'guest'], function () {
    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');

// Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
});

Route::group(['middleware' => 'auth'], function () {

    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['middleware' => 'admin'], function () {
        // Registration Routes...
        Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'Auth\RegisterController@register');

        // Users Routes...
        Route::get('/users/index', 'UserController@index')->name('admin.users.index');
        Route::get('/user/destroy/{id}', 'UserController@destroy');

    });
});

//Route::get('/nuevoUsuario', 'UserController@index');

//Route::post('/store', 'UserController@store');

app/Area.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Area extends Model
{
    use SoftDeletes;

    protected $table = 'areas';
    protected $fillable = ['area'];

    protected $dates = ['deleted_at'];
}

app/Http/Controllers/Admin/AreaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Area;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AreaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $areas = Area::orderBy('area')->get();

        return view('admin.areas.index', compact('areas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.areas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'area' => 'required|unique:areas,area|alpha'
        ]);

        Area::create([
            'area' => $request->input('area')
        ]);

        alert()->success('Área creada','El área se creo correctamente')->persistent('Close');
//        toast('Área creada','success','top-right');
        return redirect(route('admin.areas.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $area = Area::where('id', $id)->first();

        return view('admin.areas.delete', compact('area'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $area = Area::where('id', $id)->first();

        return view('admin.areas.edit', compact('area'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Area::where('id', $id)->update([
            'area' => $request->input('area')
        ]);

        return redirect(route('admin.areas.index'))->with('success', 'Área editada correctamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Area::where('id', $id)->delete();

        return redirect(route('admin.areas.index'))->with('success', 'Área eliminada correctamente.');
    }
}

resources/views/admin/areas/create.blade.php
@extends('layouts.admin')

@section('title')

    Nueva Área

@endsection

@section('content')


    <div class="card card-info">

        <!-- form start -->
        <form method="POST" action="{{route('admin.areas.store')}}" class="form-horizontal">
            @csrf

            <div class="card-body">
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Área</label>

                    <div class="col-sm-12">
                        <input type="text" class="form-control {{ $errors->has('area') ? ' is-invalid' : '' }}"
                               name="area" value="{{old('area')}}" placeholder="-"
                               autofocus required autocomplete="off">
                    </div>
                    @if ($errors->has('area'))
                        <span class="invalid-feedback d-block" role="alert">
                            <strong>{{ $errors->first('area') }}</strong>
                        </span>
                    @endif
                </div>

            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <input type="submit" class="btn btn-info float-right" value="Crear"/>
                <a href="{{route('admin.areas.index')}}" class="btn btn-default">Cancel</a>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>

@endsection

resources/views/admin/areas/delete.blade.php
@extends('layouts.admin')

@section('title')

    Eliminar Área


@endsection

@section('content')


    <div class="card card-info">

        <div class="card-body">

            <!-- form start -->
            <form method="POST" action="{{route('admin.areas.destroy', $area->id)}}" class="form-horizontal">
                @csrf
                @method('delete')

                <div class="alert alert-danger text-center" style="overflow: hidden;">

                    ¿ Eliminar el área <strong>{{$area->area}}</strong>?

                </div>

                <a href="{{route('admin.areas.index')}}" class="btn btn-default float-left">Cancel</a>

                <input type="submit" class="btn btn-danger float-right" value="Eliminar"/>

                <!-- /.card-footer -->
            </form>

        </div>
    </div>

@endsection

resources/views/admin/areas/edit.blade.php
@extends('layouts.admin')

@section('title')

    Editar Área


@endsection

@section('content')


    <div class="card card-info">

        <!-- form start -->
        <form method="POST" action="{{route('admin.areas.update', $area->id)}}" class="form-horizontal">
            @csrf
            @method('patch')

            <div class="card-body">
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Área</label>

                    <div class="col-sm-12">
                        <input type="text" class="form-control" name="area" value="{{ $area->area }}" placeholder="..." autofocus required autocomplete="off">
                    </div>
                </div>

            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <input type="submit" class="btn btn-warning float-right"  value="Editar"/>
                <a href="{{route('admin.areas.index')}}" class="btn btn-default">Cancel</a>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>


@endsection

resources/views/admin/areas/index.blade.php
@extends('layouts.admin')

@section('title')

    Areas

    <a href="{{route('admin.areas.create')}}" class="btn btn-info btn-sm">
        <i class="fa fa-plus" aria-hidden="true"></i>
    </a>

@endsection

@section('content')


    <div class="card">



        <div class="card-body ">
            @if(session()->has('success'))
                <div class="alert alert-success mb-3">
                    {{ session()->get('success') }}
                </div>
            @endif
            <table class="table-bordered table mb-2 datatables">
                <thead>
                <tr>
                    <td class="text-center">Área</td>
                    <td class="text-center">Acciones</td>
                </tr>
                </thead>
                <tbody>
                @foreach($areas as $a)
                    <tr class="text-center">
                        <th>
                            {{$a->area}}
                        </th>
                        <th>
                            <div class="btn-group">
                                <i class="fa fa-list" aria-hidden="true" data-toggle="dropdown"
                                   aria-expanded="false" style="cursor: pointer; color: #1d68a7">
                                </i>

                                <div class="dropdown-menu" role="menu" x-placement="bottom-start"
                                     style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(67px, 38px, 0px);">
                                    <a class="dropdown-item" href="{{route('admin.areas.edit', $a->id)}}">
                                        <i class="fa fa-pencil-alt" aria-hidden="true"></i>
                                        Editar
                                    </a>
                                    <a class="dropdown-item" href="{{route('admin.areas.show', $a->id)}}">
                                        <i class="fa fa-trash" aria-hidden="true"></i>
                                        Eliminar
                                    </a>
                                </div>
                            </div>
                        </th>
                    </tr>
                @endforeach

                </tbody>
            </table>

            {{--<div class="pagination-links">--}}
                {{--{{$areas->links()}}--}}
            {{--</div>--}}
        </div>


    </div>


@endsection